extends Node

# Saved selection for this scene
static var saved_selection : Vector2i = Vector2i(-1, -1)

# Draws the scene
static func draw_scene():
	globals.set_return_action(func():
		globals.character_creation_background = null
		globals.set_scene("scene_game_a", true)
	)
	globals.set_cursor_x(1)
	globals.write("This is your character's equipment. You can change it here.", "Yellow")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write("Armor")
	globals.set_cursor_x(33)
	globals.write("  D PRT OUTPUT", "DimGray")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("HEA", globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("CHE", globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("HAN", globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("LEG", globals.savegame.player)
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write("Arms")
	globals.set_cursor_x(33)
	globals.write("  D PRT OUTPUT", "DimGray")
	globals.set_cursor_x(49)
	globals.write("  A DMG OUTPUT", "DimGray")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("MAI", globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("OFF", globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_slot("RAN", globals.savegame.player)
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write("Accessories")
	globals.set_cursor_x(33)
	globals.write("  D PRT OUTPUT", "DimGray")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_accessory(0, globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_accessory(1, globals.savegame.player)
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.print_accessory(2, globals.savegame.player)
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
