extends Node

# Saved selection for this scene
static var saved_selection : Vector2i = Vector2i(-1, -1)

# Draws the scene
static func draw_scene():
	globals.set_return_action(func():
		globals.set_scene("scene_game_a")
	)
	globals.set_cursor_x(1)
	globals.write("This is the map of all the areas and sites you explored.", "Yellow")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_xy(0, 19)
	globals.write("-".repeat(80))
	globals.set_cursor_xy(1, 20)
	globals.write_selectable(func():
		globals.combat = Combat.create([Character.create_random("Red Dragon"), Character.create_random("Beastman Skeleton"), Character.create_random("Beastman Skeleton"), Character.create_random("Beastman Skeleton")])
	)
	globals.modify_cursor_x(-2)
	globals.write("◄ ")
	globals.write("    ")
	globals.modify_cursor_x(1)
	globals.write("    ")
	globals.modify_cursor_x(1)
	globals.write("    ")
	globals.modify_cursor_x(1)
	globals.write("    ")
	globals.modify_cursor_x(1)
	globals.write(" ?? ", "Gray", "DimGray")
	globals.modify_cursor_x(1)
	globals.write(" -- ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" -- ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" Gh ", "Black", "White")
	globals.modify_cursor_x(1)
	globals.write(" Ms ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" -- ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" -- ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" -- ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" -- ", "Black", "DarkGray")
	globals.modify_cursor_x(1)
	globals.write(" ?? ", "Gray", "DimGray")
	globals.modify_cursor_x(1)
	globals.write("    ")
	globals.modify_cursor_x(1)
	globals.write_selectable(func():
		globals.combat = Combat.create([Character.create_random("Beastman Skeleton")])
	)
	globals.modify_cursor_x(-2)
	globals.write("►")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
