extends Node

# Saved selection for this scene
static var saved_selection : Vector2i = Vector2i(-1, -1)

# Draws the scene
static func draw_scene():
	globals.set_return_action(func():
		globals.set_scene("scene_character_creation_e", true)
	)
	globals.set_cursor_x(1)
	globals.write("Tora hit Skeleton Warrior for 7 points of damage!", "Yellow")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write("Party")
	globals.set_cursor_x(33)
	globals.write("Enemies")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	for friend in globals.savegame.combat.friends:
		globals.set_cursor_x(1)
		globals.modify_cursor_y(1)
		#globals.write_selectable(func():
			#globals.set_scene("ass", true)
		#)
		globals.write(friend.get_name(), "Gray")
	globals.set_cursor_xy(0, 3)
	for enemy in globals.savegame.combat.enemies:
		globals.set_cursor_x(33)
		globals.modify_cursor_y(1)
		globals.write(enemy.get_name(), "Gray")
	globals.set_cursor_xy(0, 15)
	globals.write("-".repeat(80))
	globals.set_cursor_xy(0, 17)
	globals.write("-".repeat(80))
	if globals.combat_current != null:
		globals.set_cursor_xy(1, 16)
		globals.write(globals.combat_current.get_name())
		globals.set_cursor_x(1)
		globals.modify_cursor_y(2)
		globals.write("Health")
		globals.set_cursor_x(17)
		globals.write("27 out of 31")
		globals.set_cursor_x(1)
		globals.modify_cursor_y(1)
		globals.write("Melee")
		globals.set_cursor_x(17)
		globals.write("+3 4-10")
		globals.set_cursor_x(1)
		globals.modify_cursor_y(1)
		globals.write("Ranged")
		globals.set_cursor_x(17)
		globals.write("+2 3-6")
		globals.set_cursor_x(1)
		globals.modify_cursor_y(1)
		globals.write("Defences")
		globals.set_cursor_x(17)
		globals.write("+1 2-4")
	if globals.combat_target != null:
		globals.set_cursor_xy(33, 16)
		globals.write(globals.combat_target.get_name())
		globals.set_cursor_x(33)
		globals.modify_cursor_y(2)
		globals.write("Health")
		globals.set_cursor_x(49)
		globals.write("27 out of 31")
		globals.set_cursor_x(33)
		globals.modify_cursor_y(1)
		globals.write("Melee")
		globals.set_cursor_x(49)
		globals.write("+3 4-10")
		globals.set_cursor_x(33)
		globals.modify_cursor_y(1)
		globals.write("Ranged")
		globals.set_cursor_x(49)
		globals.write("+2 3-6")
		globals.set_cursor_x(33)
		globals.modify_cursor_y(1)
		globals.write("Defences")
		globals.set_cursor_x(49)
		globals.write("+1 2-4")
