extends Node

# Saved selection for this scene
static var saved_selection : Vector2i = Vector2i(-1, -1)

# Draws the scene
static func draw_scene():
	globals.set_return_action(func():
		globals.set_scene("scene_menu_c", true)
	)
	globals.set_cursor_x(1)
	globals.write("Continue on your quest or try to return home.", "Yellow")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write("Area : Ruined Village [  ‐↓‐‐●‐‐‐‐‐‐‐↑‐‐]")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write("Exploration")
	globals.set_cursor_x(17)
	globals.write("Sites")
	globals.set_cursor_x(0)
	globals.modify_cursor_y(1)
	globals.write("-".repeat(80))
	globals.set_cursor_x(1)
	globals.modify_cursor_y(1)
	globals.write_selectable(func():
		globals.savegame.combat = Combat.create([globals.savegame.player], [Character.create(null, null, globals.races.filter(func(n): return n["name"] == "Red Dragon")[0], null), Character.create(null, null, globals.races.filter(func(n): return n["name"] == "Red Dragon")[0], null)])
		globals.set_scene("scene_game_combat_a")
	)
	globals.write("Explore")
	globals.set_cursor_xy(17, 6)
	globals.write_selectable(func():
		globals.set_scene("scene_game_combat_a")
	)
	globals.write("Village Tract")
	globals.set_cursor_xy(10, 10)
	globals.write("                    ←●●‐‐‐●↓→")
	globals.set_cursor_xy(10, 11)
	globals.write("               ←↓‐‐●●‐‐●‐●‐↑●▪▫")
	globals.set_cursor_xy(10, 12)
	globals.write("          ●‐‐‐‐●↕‐‐●‐→          ")
	globals.set_cursor_xy(10, 13)
	globals.write("               ←↑→              ")
	
	#globals.set_cursor_xy(11, 9)
	#globals.write("Ruined Village")
	#globals.set_cursor_x(10)
	#globals.modify_cursor_y(1)
	#globals.write("----------------")
	#globals.set_cursor_x(11)
	#globals.modify_cursor_y(1)
	#globals.write("12           ?")
	#
	#globals.set_cursor_xy(31, 5)
	#globals.write("Outer Castle Bailey")
	#globals.set_cursor_x(30)
	#globals.modify_cursor_y(1)
	#globals.write("---------------------")
	#globals.set_cursor_x(31)
	#globals.modify_cursor_y(1)
	#globals.write("12                ?")
	#globals.modify_cursor_y(2)
	#globals.set_cursor_x(28)
	#globals.write("    ↑")
	#globals.set_cursor_x(28)
	#globals.modify_cursor_y(1)
	#globals.write("  ● ●")
	#globals.set_cursor_x(28)
	#globals.modify_cursor_y(1)
	#globals.write("● @ ● ●")
	#globals.set_cursor_x(28)
	#globals.modify_cursor_y(1)
	#globals.write("●   ●   ●")
	
	#globals.set_cursor_xy(10, 9)
	#globals.write("          ", "DimGray")
	#globals.set_cursor_xy(10, 10)
	#globals.write("  ▒▒▒▒▒▒    ", "DimGray")
	#globals.set_cursor_xy(10, 11)
	#globals.write("  ▒▒  ▒▒▒▒  ", "DimGray")
	#globals.set_cursor_xy(10, 12)
	#globals.write("            ", "DimGray")
	#globals.set_cursor_xy(12, 10)
	#globals.write("Tr", "Black", "Cyan")
	#globals.set_cursor_xy(14, 10)
	#globals.write("▪▫▪▫▪▫", "Black", "DarkGray")
	#globals.set_cursor_xy(12, 11)
	#globals.write("▪▫██▪▫", "Black", "DarkGray")
	#globals.set_cursor_xy(12, 12)
	#globals.write("Dt", "Black", "Red")
	#globals.set_cursor_xy(10, 9)
	#globals.write("%/%/%/%/%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(10, 10)
	#globals.write("%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(18, 10)
	#globals.write("%/%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(10, 11)
	#globals.write("%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(14, 11)
	#globals.write("%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(20, 11)
	#globals.write("%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(10, 12)
	#globals.write("%/%/%/%/%/%/", "Black", "DarkOrange")
	#globals.set_cursor_xy(12, 10)
	#globals.write("Tr", "Black", "Cyan")
	#globals.write("┌───┐   ┌───┬───┐")
	#globals.set_cursor_xy(10, 11)
	#globals.write("│ A │   │ A │ A │")
	#globals.set_cursor_xy(10, 12)
	#globals.write("├   ┼───┼───┼───┤")
	#globals.set_cursor_xy(10, 13)
	#globals.write("│ A   A │ A │ A │")
	#globals.set_cursor_xy(10, 14)
	#globals.write("├───┼───┼───┼───┘")
	#globals.set_cursor_xy(10, 15)
	#globals.write("│ A │ A │ A │")
	#globals.set_cursor_xy(10, 16)
	#globals.write("└───┴───┴───┘")
	#globals.set_cursor_x(1)
	#globals.write("Walking through the mines you suddenly hear a powerful shriek.", "Red")
	#globals.set_cursor_x(1)
	#globals.modify_cursor_y(1)
	#globals.write("The sound certainly comes from somewhere around you.", "Red")
	#globals.set_cursor_x(0)
	#globals.modify_cursor_y(1)
	#globals.write("-".repeat(80))
	#globals.set_cursor_x(1)
	#globals.modify_cursor_y(1)
	#globals.write_selectable(func():
		#globals.set_scene("scene_game_a")
	#)
	#globals.write("Ok")
	#globals.print_stats(globals.character_creation_race, globals.character_creation_background)
